version: '3.8'
services:
  app:
    build: .
    image: video-highlight-generator
    ports:
      - "8000:8000"
    environment:
      - DB_PATH=/app/data/video_highlight_generator.db
    volumes:
      - ./data:/app/data
      - ./media:/data/media # Mount your media folder here
